const driveImageUrl = (fileId: string) => `https://lh3.googleusercontent.com/d/${fileId}`

export const googleDriveImageFolderUrl =
  'https://drive.google.com/drive/folders/1U2OJUG4Z9N_u1jIYrMI07uYhmavuHvYO'

export const imageUrls = {
  favicon: driveImageUrl('1lHDHNuzB9jF8mDQ9RbuamPOzmszcxd71'),
  logo: driveImageUrl('17FkuxOBct41qq94QwLPwdQxSOv1me4MN'),
  donation: {
    acledaLogo: driveImageUrl('1ZshbEMfcy4n7bMBcr2B2gx6dB4tYqvIj'),
  },
  programs: {
    childProtection: driveImageUrl('1nMadwzd7BFV4uDOZILh3ir1rFnLoR92L'),
    childProtection1: driveImageUrl('1omb6wmt0nfs_RDkMjF8quBJ9dzSfpO53'),
    childProtection2: driveImageUrl('14M_kqxOmAYfkfg3IwVr5ijFE0f-20V0G'),
    childProtection3: driveImageUrl('1HmA2ekQZDZppMYB2rbTey3FJLVR7U6U_'),
    education: driveImageUrl('1PeWfmnkBPz83fFYNtydsio9LLFgp1HOr'),
    educationHero: driveImageUrl('1oLliPMim5_YsBSsstLo7ZdV3id5n5OQG'),
    environment: driveImageUrl('1_TlqRYDZBH8rhnPumIRysRO4zTcTzr6r'),
    environmentHero1: driveImageUrl('1TyEkPpMaouSYyYyWMcpmeCWAtBnM5ZtN'),
    hero1: driveImageUrl('1whUvuDT8FTTN9EtYXtMtRFlonML67aJv'),
    hero2: driveImageUrl('1QtIOaAYlwHCwO7l7_uuvxwdA_ONIRB98'),
    hero3: driveImageUrl('15dMob3OSDw-nxju4VuCIB0BiRHT0P5Od'),
    hero4: driveImageUrl('1DMorxbgVk5RLsUyb84gRIKUojkAzwzW7'),
    livelihood: driveImageUrl('1b9AzdY0Mpqe0jfvEWg2WRSyB84_asWSY'),
    livelihoodHero1: driveImageUrl('1l5NLDZCjmJcRM8JoSPFyUSHKOG5Z-dJa'),
    livelihoodHero2: driveImageUrl('1hzIL6Cr_qXFPPtuIjJe0CLn3ffjl3wIy'),
    livelihoodHero3: driveImageUrl('1Hrzqid2Szxv3ivPFsLVaMdjQqQSW9SLx'),
    livelihoodHero4: driveImageUrl('1mdldHtTI8rsL0j63z7a1YAWGyp4QThaj'),
  },
  home: {
    child: driveImageUrl('1b9AzdY0Mpqe0jfvEWg2WRSyB84_asWSY'),
    education: driveImageUrl('1A48ssE-xq_eT1jh4EvJ4xqAaIWz2d7uG'),
    environment: driveImageUrl('1MET3GHWBTMWkusil0thU9nmWhjFayxzb'),
    livelihood: driveImageUrl('1DMorxbgVk5RLsUyb84gRIKUojkAzwzW7'),
  },
  education: {
    intro: driveImageUrl('1aiC3FEAQNS6IWV5Ohdtk5H79__iQBRJ4'),
    reading: driveImageUrl('1HebMqX_egm3EsgYaSEYbg0_gB0lmmm3N'),
    study: driveImageUrl('1_altRLSSbZp8SU6S9ngYP8JVvGff6FFL'),
    teacher: driveImageUrl('14rjiFllDs3Z_CDeoN9GjTS2fWVJ9y96u'),
  },
  impact: {
    hero: driveImageUrl('1ST8oaWgzUUG_FyLpTArGe1_44uusj3t0'),
    forest: driveImageUrl('1p5woZaoZ5_HsqAw7nGWQt9UB5FrBXyn8'),
    village: driveImageUrl('1cdGohoZ1L4P75nCgBOB_X9bmJtwBxyxw'),
  },
  maps: {
    cambodia: driveImageUrl('1uRmjMjgSUryEA0TtvU3PkpWpubAyd19m'),
    cambodiaOffices: driveImageUrl('1Z1M4cwXa3r8T7tEAsdtso3qnOD0XIkku'),
    locationIcon: driveImageUrl('1qqImiOGVC_1TDzFOAFxMphuaLjFupRhF'),
    preyVeng: driveImageUrl('1aR1QZwhDtINQb-i1p9K72iLqOH0lNGPl'),
    svayRieng: driveImageUrl('1dwJc7ia13bNZiJjXoALTgazgFOsnKRuK'),
    timeline1994: driveImageUrl('1gtfK8YY-fXHTX-PLLYJ_KqW5cahN_HVi'),
    timeline1998: driveImageUrl('1j1isQHv7zkvrH0FdIW20-opA0zKiT6O3'),
    timeline2003: driveImageUrl('1D5vN0Ai8yLpp-hCYaAYTHB_YUW5w5tOZ'),
    timeline2007: driveImageUrl('1G_A5kfMX7nFmgNMiI0HCBXyF_u9k2LqB'),
    timeline2011: driveImageUrl('1hg2OwuCGQkrxJM9PNgOM65oRajMztXCr'),
    timeline2014: driveImageUrl('1-5Qbo7LDlOnNlAwG-1KxV7aVgn5UKi46'),
    timeline2018: driveImageUrl('18bqG1Z7rIYVf3oilhhlKJfrL7BazVSxc'),
    timeline2019: driveImageUrl('1DBocc-nmcTM3hY6Jd1TGa0fDhWJBbBfO'),
    timeline2022: driveImageUrl('13faFB89oB5fI-f4Cty0oeGDpLSPhQjnb'),
    timeline2024: driveImageUrl('1iTw2YGL_fzfyP6UNFlrm-xRhJ_kKJudA'),
  },
  news: {
    certificate: driveImageUrl('1hX1B6dQBpobmdcqcJ1NYi50jsyXAIpu5'),
    preschool: driveImageUrl('13Dc1t4n20sJz82rCno0tkI9YiG2u3vhC'),
    student: driveImageUrl('16aBVVPZFAeCLfRk8flYXrYZ-jxVg0zsh'),
    wash: driveImageUrl('1Ox0LNIT0ZZ1xprkuwPsKTtXU--DW_KIh'),
    water: driveImageUrl('1KVZgPZ7vq0CgKtBbS-dl8oJBeYdTkBx4'),
  },
  partners: {
    undp: driveImageUrl('1Qm2I-1nY3vsbXo3zqvrGGWGZfbY6Rt25'),
    adb: driveImageUrl('1L2_lFl8qMAml1Bd81-2A_eJdkGp5aQOM'),
    oxfam: driveImageUrl('1UhwXf-GhNgOr7kBxIOGh3FyNOJ-wRZa7'),
    breadForTheWorld: driveImageUrl('1R0Xyd39Wswo85i-nF0dCXgkNpD_DZpzE'),
    misereor: driveImageUrl('1TNFu8bGrZWu0Oh7TZ6ayIZzpb8vUmZOb'),
    europeanUnion: driveImageUrl('1etASkXAiPo1bqObnvQOftFa2Fkoq0zb6'),
    usaidWinrock: driveImageUrl('1rEieY3Du6PHdZovSTs6nVrftcev2KXA1'),
    diakonia: driveImageUrl('1vj_V4eKwBM9Gjcui5bQBVzzWAaixROYC'),
    heinrichBoll: driveImageUrl('1Zs7eihVkT9voNK2EOJrFxX-nFTMS6ivv'),
    caritas: driveImageUrl('1NdehUpufRuQVoIYdFOlRWkgHkZ0QCCYa'),
  },
  volunteer: {
    buddhistEducation: driveImageUrl('1h8rVFA3DbXADZsk8FNVj_5dPpurJ2v6c'),
    childProtection: driveImageUrl('1QR07Wk2T-LU_s5dSVGHsSrqdhWpePoY4'),
    communityForestry: driveImageUrl('1QnosDkLGAXV_x30-6EdUO_Ga24sXDNeA'),
    livelihood: driveImageUrl('1pEIPnll9s5gyKAP6IcVPg6xk5ezZ0TtF'),
    mobileLibrary: driveImageUrl('13jVkDXyOQ8pnDp7q7pbQ57cB3EvcRKeG'),
    hero: driveImageUrl('15fG5tyBvMNhFLA7Ed4XN9R946Wqadwua'),
    washSchool: driveImageUrl('1022x-_ULcvB15hMyTIcyEMhnHNqSa5UC'),
  },
} as const
